name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  tests-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x, 20.x, 22.x]
        include:
          - os: ubuntu-24.04-arm
            node-version: 22.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check Node.js version
        run: node -pe process.versions
      - name: Install module
        run: npm install
      - name: Run tests
        run: npm test
  tests-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        node-version: [16.x, 18.x, 20.x, 22.x]
        include:
          - os: macos-13
            node-version: 22.x
    runs-on: ${{ matrix.os }}
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Check Node.js version
        run: node -pe process.versions
      - name: Install module
        run: npm install
      - name: Run tests
        run: npm test
  tests-windows:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x, 20.x, 22.x]
        include:
          - os: windows-2025
            node-version: 22.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check Node.js version
        run: node -pe process.versions
      - name: Install module
        run: npm install
      - name: Run tests
        run: npm test
